# Generated by Django 2.0 on 2017-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(choices=[('ENG', 'England'), ('ESP', 'Spain'), ('ITA', 'Italy'), ('FRA', 'France'), ('DEU', 'Germany')], max_length=3)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
    ]
