# Generated by Django 2.0 on 2017-12-14 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=3)),
                ('position', models.CharField(choices=[('goalkeeper', 'GK'), ('defender', 'D'), ('midfielder', 'M'), ('forward', 'F')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
            ],
        ),
    ]
