# Generated by Django 2.0 on 2017-12-15 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substituted_in', models.IntegerField(default=0)),
                ('substituted_out', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('yellow_red_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('chances_created', models.IntegerField(default=0)),
                ('successful_crosses', models.IntegerField(default=0)),
                ('crosses', models.IntegerField(default=0)),
                ('successful_tackles', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('shots_saved', models.IntegerField(default=0)),
                ('shots_faced', models.IntegerField(default=0)),
                ('penalties_faced', models.IntegerField(default=0)),
                ('penalties_saved', models.IntegerField(default=0)),
                ('fouls_committed', models.IntegerField(default=0)),
                ('shots_on_goal', models.IntegerField(default=0)),
                ('shots_off_goal', models.IntegerField(default=0)),
                ('shots_blocked', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('penalty_goals', models.IntegerField(default=0)),
                ('match_date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
    ]
