# Generated by Django 2.0 on 2017-12-22 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_matchstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('transfer_balance', models.IntegerField(default=200000000)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Matchweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Club')),
                ('d_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_four', to='api.Player')),
                ('d_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_one', to='api.Player')),
                ('d_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_sub', to='api.Player')),
                ('d_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_three', to='api.Player')),
                ('d_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_two', to='api.Player')),
                ('f_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_one', to='api.Player')),
                ('f_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_sub', to='api.Player')),
                ('f_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_three', to='api.Player')),
                ('f_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_two', to='api.Player')),
                ('gk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk', to='api.Player')),
                ('gk_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk_sub', to='api.Player')),
                ('m_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_four', to='api.Player')),
                ('m_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_one', to='api.Player')),
                ('m_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_sub', to='api.Player')),
                ('m_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_three', to='api.Player')),
                ('m_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_two', to='api.Player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Matchweek')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.League'),
        ),
        migrations.AddField(
            model_name='club',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(to='api.Player'),
        ),
    ]
