# Generated by Django 2.0 on 2018-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171222_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='club',
        ),
        migrations.AddField(
            model_name='roster',
            name='manager_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
