# Generated by Django 2.0 on 2018-01-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180124_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchweek',
            name='week_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
